Repository seonyae-park/hello-charlie, pull requests merged in 2024-07, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation

#9 feat: set up the environment for nextjs
  .eslintrc.json
  .gitignore
  README.md
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/next.svg
  public/vercel.svg
  src/app/calendar/layout.tsx
  src/app/calendar/page.tsx
  src/app/home/layout.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/login/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/settings/layout.tsx
  src/app/settings/page.tsx
  src/app/ui/favicon.ico
  src/app/ui/fonts.ts
  src/app/ui/globals.css
  src/app/user/layout.tsx
  src/app/user/page.tsx
  tailwind.config.ts
  tsconfig.json
Labels: feature

#17 environment: setup the config for release-drafter
  .github/drafter-config.yml
Labels: environment

#18 chore: modify configs for autolabeler
  .github/drafter-config.yml
Labels: chore

#16 environment: set up release drafter action
  .github/workflows/release-drafter.yml
Labels: chore

#21 chore: add code owners and pr template
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: chore

#23 chore: enable autolabeler in pr
  .github/workflows/release-drafter.yml
Labels: chore
